### PR TITLE
ColdFusion 9 errors fixed

### PR DESCRIPTION
**Pull request by binarygeek**
I downloaded this source and tried to run it on ColdFusion 9 but got various errors. Made the changes and committed them. Didn't test these changes in any other CF engine.

### CODE REVIEW

**Comment by benorama** [comment]
All your errors are specific to ColdFusion 9 : the Facebook SDK requires ColdFusion 9.0.1 (which is a recommended upgrade).

**Comment by binarygeek** [comment]
damn it. you're right. argh! why doesn't adobe not put the most up to date version when you download it from them? grrr.

My bad!

**Comment by benorama** [comment]
Yes, I hope this will be solved in CF 10 with auto-update... ;)

**Comment by binarygeek** [comment]
yes it has. FINALLY! got my hands on it and was playing around with it. Worried me the first time I used it because the "test" update they pushed didn't work. Although when they pushed a real update to the beta, it worked and was SO much nicer!

-K

**Pull request closed without merging**
